### ISSUE TITLE
RequestParameter.Category is read-only

### ISSUE THREAD

**Issue by sbohmig** [Nordes/CognitiveServices.Translator.Wrapper#10]
Please amend code:

        /// <summary>
        /// A string specifying the category (domain) of the translation. This parameter
        /// is used to get translations from a customized system built with Microsoft Translator Hub. Default value is: general.
        /// </summary>
        public string Category => "general";

==> 
        public string Category { get; set; } = "general";

**Comment by Nordes** [comment]
Done.
